### ISSUE TITLE
Issue of Circularity 

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/PheValuator#23]
Hi,

I was going through all the issues in github to recap and also read your paper. Quick questions on "Circularity" and how to avoid it.

Let's say I have used PheKB algorithm to build my XSpec cohort.  Now as we use "excludedconcepts" parameter in the function "CreatePhenoTypeModel", I understand it ignores all the concepts used in the XSpec cohort definition. 

a) May I kindly check with you on why do we have to exclude this concepts used to build XSpec and XSens cohorts? I am aware through exercise that if we don't exclude it will result in error/warning message. But may I check why do we have to exclude?  Because usually XSpec cohorts involve well-thought out cohort definition (including most relevant single/multiple data domain elements) to get highly positive items. If we aren't going to consider these codes/data elements, will it not impact our prediction/model performance to generate labels? After-all they were chosen to be used under XSpec in the first place because they can clearly say whether a person is positive or negative? So why do we exclude them?

b) let's say our clinicians came up with a new phenotype algorithm called "Magic" to identify T2DM patients.

Am I right to understand that XSpec cohort definition will always and must be different from the Phenotype algorithm (Magic) that we intend to assess.

c) To evaluate our Phenotype Algorithm ("Magic"), Am I right to understand it's essential to have a XSpec cohort definition which performs better than "Magic". Meaning XSpec cohort definitions are used to generate the probabilistic gold standard. So they ought to be really top-class and in a sense better than the Phenotype algorithm (Magic) itself.

Only then it can ensure a fair assessment of our in-house Phenotype algorithm ("Magic"). Right?

**Comment by jswerdel** [comment]
a) As you noted, we need to exclude them or there will be perfect separation between the noisy positives and negatives causing the model to fail.  It's true that these may be good predictors for the model.  However, the condition code for the HOI may have been placed in the person's record either as a rule out code or in error.  So eliminating the condition code is OK - it is based on an opinion of a physician who based his/her opinion on the tests, symptoms, prior comorbid conditions, etc. from the patient.  What we don't want to eliminate (exclude) from the model process are the tests, symptoms, prior comorbid conditions, etc - these are left in a valuable predictors.  This is why we don't use complex phenotype logic to create the xSpec cohort - we try to develop it based just on condition codes specifically for the HOI.  Here we are making the assumption that a person with 5 codes for lung cancer has a high probability of having lung cancer.  A person with one code for lung cancer, a procedure for a lung biopsy, and chemotherapy specific for lung cancer also very likely has lung cancer.  However using that definition excludes many valuable predictors for lung cancer and weakens the model.  Excluding just the lung cancer prediction code may weaken the model somewhat - but the presence of the code is subjective as opposed to the objective codes for biopsy and chemotherapy,

b) Not really - the definition for an xSpec  for T2DM, say 10 condition codes for T2DM, is a perfectly valid phenotype algorithm for T2DM.  It can be used in a study as long as you are OK with the (probably)  low sensitivity of the algorithm.  In most cases though, you will want to use another algorithm for your study.  This is the value of PheValuator - to test the performance characteristics of an algorithm to be used in your study.  For example, your "magic" algorithm may have great PPV but very low sensitivity.

c) You are right as long as by "better" you mean higher PPV. i.e., the probability of a subject included in your xSpec cohort being a case is very high.  You can use the "magic" algorithm, if you feel the PPV is high, but you are going to pay a price if, as I discussed above it forces you to exclude many valuable predictors.

In fact, the PPV of the xSpec cohort can be evaluated (in step 3 of the process) just like any other algorithm.  And, depending on the HOI, the PPV may only be 80-85%.  Some HOI are hard to determine from a claims database.  PheValuator will struggle with HOI such as psoriasis which are difficult to distinguish from other HOI - many of the elements in the patients record are very similar to many other diseases, say, eczema.  A cliniciam looking at the patient's profile would struggle just as PheValuator struggles.  Subjects with lung cancer have many elements in their record that make it more obvious that the person has lung cancer - the model does well just as a clinician will do well in examining the patient's profile

**Comment by SSMK-wq** [comment]
Hi @jswerdel 

wrt b) question

b)

> the definition for an xSpec for T2DM, say 10 condition codes for T2DM, is a perfectly valid phenotype algorithm for T2DM

Let's take this example. 

So, do you mean the below scenario is possible?

XSpec >= 10 condition codes (C1......C10) (which is Magic cohort definition)
Phenotype Algorithm that we intend to assess (Magic) >=10 condition codes (C1....C10)

a) Like you said both XSpec and PA are same. So this is possible?

But doesn't this violate the point a) that you stated above. 

Because if I have the same definition then the model will drop all these conditions C1....C10 and build a feature set (which might have less predictive power than C1...C10).

Later evaluation cohort will also contain features (which will exclude C1...C10) and trained model be applied on them to produce the probabilistic gold standard (Which will be less accurate because of lower predictive features) because our clinician told that C1...C10 are highly predictive features (which are dropped now). 

Now, I have labels of subjects generated based on Magic (Phenotype Algorithm) generated using Atlas.

b) Now we compare these Atlas subject_ids with Probabilistic gold standard. Right?

c) But is this a fair comparison? Meaning when we know that we are dropping highly predictive features and using lower predictive features to generate probabilistic values (which may not be accurate). Can we rely on these probabilistic values? May I know your reasoning behind allowing XSpec definition and Test Phenotype Algorithm definition (Magic) to be the same? 

d) In your example cohorts defined in paper, are they the same? 

f) Can I have those json files or cohort id in public Atlas?

**Comment by SSMK-wq** [comment]
@jswerdel  - Modified the question with little bit more info. Realized it was too verbose earlier...Thanks

**Comment by jswerdel** [comment]
a) yes - the definition for the xSpec cohort is a reasonable definition for a cohort.  It may not have the characteristics you want for a study (very low sensitivity) but it could be used.
As a note though - if you use that definition for your xSpec for model building, you must exclude the codes for the labs and the drugs

b) 
1) In modeling an issue may arise if you use the probability for a subject that was used in model building.  The model was trained on that subject so the probability may be higher than it would if it was not trained on that subject.  In our case, when we test phenotypes in the third step of the process we test using the evaluation cohort built in the second step of the process.  The evaluation cohort was built specifically excluding all the subjects used in the model building process.  So when you run the third step that tests a phenotype, you are only using the members of the phenotype to test that were not used in the model building process.  Example: let's say there are 5000 subjects in the xSpec cohort and 1500 were used to build the model.  The other 3500 subjects of the cohort are fair game to be included in the evaluation cohort.  These 3500 (or however many were actually selected for the evaluation cohort) would be used to evaluate the cohort to test, in this case the xSpec cohort.
2) I would not recommend using that definition for the xSpec because it eliminates too many good predictors from the model (drugs, measurements).  Otherwise, it could be used in a study as long as the performance characteristics are suitable for the study.
c) See: http://atlas-demo.ohdsi.org/#/cohortdefinitions - the definitions used in the study are named with the prefix [PheVal]

**Comment by SSMK-wq** [comment]
Regarding b) 

1) Actually I was coming from different perspective. My question wasn't on probability of subjects under Xpec or evaluation cohort... Instead it was on the reliability of the cohort definition... Meaning if we are going to use our locally developed phenotype algorithm (Magic - whose performance we intend to assess) as XSpec cohort , can we rely on those results? Because our Magic phenotype is not validated across sites and we don't really know how good it is.. Of course the rules for magic was developed with the help of clinicians 

What I was thinking was

> Best combination 

XSpec = PheKB (validated across sites and have read that it's good) 
 Test phenotype = Magic


> Not best combination 

 XSpec = Magic (not validated across many sites and brand new) 

Test phenotype = Magic

What do you think about these two combinations? Our objective is to assess the performance of magic 

I remember about our discussion yesterday where we touched upon how XSpec should be better than Test PA.. Then 1st option is the best?

**Comment by jswerdel** [comment]
The goal for xSpec is to use a cohort definition where the subjects in the cohort have a high likelihood of having the disease.  We use the 5/10X condition code cohort because we think that any subject that has 5/10 condition codes for the HOI is very likely to have the HOI.  The PheKB definition is good but it was likely designed to balance the sensitivity and PPV.  xSpec doesn't have this constraint - it is designed to optimize PPV with no concern for sensitivity.  The caveat is that the definition should not be so specific that the population in the xSpec cohort is very different than the overall population with the HOI.
Here using PheKB is OK but it has the limitation that it forces the exclusion of many possible predictors.
If you ask clinicians if someone with 10 condition codes in his/her record likely has the HOI, they will likely say yes.

**Comment by SSMK-wq** [comment]
okay got it.  Thanks. This issue can be closed...
