### ISSUE TITLE
Question - Expected Value - Cut points

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/PheValuator#8]
Hi,

I have been reading about the Phevaluator package and it's amazing.

But I have a quick question on what does "EV" (Expected Value) mean under "Cut points" parameter?

I understand we have usually choose a threshold of 0.5 to discriminate the classes (positive or negative). Here cut points are nothing but thresholds am I right?

> 0.5 - +ve
<0.5 - -ve

But may I know what does "EV" mean? What value is chosen to discriminate between the classes?

How different it is from other threshold values like 0.1,0.2,0.3,0.4.0.5,0.6.0.7 etc

Can help with this?

**Comment by jswerdel** [comment]
The expected value (EV) calculates the performance using the probability rather than a cutpoint.  If a subject in the evaluation cohort is included in the phenotype algorithm (cohort definition) then that subject's probability (p) is added to the true positive (TP) bucket and 1-p is added to the false positive bucket.  If the person was not included in the phenotype algorithm, then 1-p is added to the true negative bucket and p is added to the false negative (FN) bucket.  This is done for each person in the evaluation cohort.  The sums of the 4 buckets are then used to calculate the performance characteristics of the phenotype algorithm.  For example, sensitivity is calculated as the sum of the TP's divided by the sum of the TP's plus the sum of the FN's.
